import type { Vacancy, SearchQuery, Resume, Analytics } from './types'

export const mockVacancies: Vacancy[] = [
  {
    id: '1',
    externalId: '123456789',
    source: 'hh',
    title: 'Senior Frontend Developer',
    company: 'Яндекс',
    companyLogo: 'https://hh.ru/employer-logo/289027.png',
    salary: { from: 280000, to: 400000, currency: 'RUB', gross: false },
    experience: '3-6 лет',
    employment: 'Полная занятость',
    schedule: 'Удаленная работа',
    location: 'Москва',
    description: 'Мы ищем опытного Frontend-разработчика для работы над сервисами Яндекса. Вам предстоит разрабатывать высоконагруженные веб-приложения с использованием современных технологий.',
    requirements: 'Опыт коммерческой разработки от 3 лет. Глубокое знание JavaScript/TypeScript. Опыт работы с React.',
    responsibilities: 'Разработка новых фичей. Code review. Оптимизация производительности.',
    skills: ['React', 'TypeScript', 'Node.js', 'GraphQL', 'CSS-in-JS'],
    url: 'https://hh.ru/vacancy/123456789',
    publishedAt: '2024-01-15T10:00:00Z',
    createdAt: '2024-01-15T12:00:00Z',
    responses: 142,
    views: 2340,
    isAnalyzed: true,
    matchScore: 92,
    aiAnalysis: 'Отличное совпадение! Ваш опыт с React и TypeScript полностью соответствует требованиям. Рекомендуется подчеркнуть опыт работы с высоконагруженными проектами.',
    isFavorite: true,
    status: 'new'
  },
  {
    id: '2',
    externalId: '987654321',
    source: 'hh',
    title: 'Python Backend Developer',
    company: 'Сбер',
    salary: { from: 250000, to: 350000, currency: 'RUB', gross: true },
    experience: '1-3 года',
    employment: 'Полная занятость',
    schedule: 'Гибридный график',
    location: 'Санкт-Петербург',
    description: 'Приглашаем Backend-разработчика в команду платформы данных. Работа над микросервисной архитектурой.',
    skills: ['Python', 'FastAPI', 'PostgreSQL', 'Redis', 'Docker', 'Kubernetes'],
    url: 'https://hh.ru/vacancy/987654321',
    publishedAt: '2024-01-14T14:30:00Z',
    createdAt: '2024-01-14T16:00:00Z',
    responses: 89,
    views: 1560,
    isAnalyzed: true,
    matchScore: 78,
    aiAnalysis: 'Хорошее совпадение по стеку. Рекомендуется указать опыт работы с микросервисами и контейнеризацией.',
    isFavorite: false,
    status: 'viewed'
  },
  {
    id: '3',
    externalId: '456789123',
    source: 'hh',
    title: 'DevOps Engineer',
    company: 'VK',
    salary: { from: 300000, to: 450000, currency: 'RUB' },
    experience: '3-6 лет',
    employment: 'Полная занятость',
    schedule: 'Удаленная работа',
    location: 'Москва',
    description: 'Ищем DevOps-инженера для автоматизации инфраструктуры и CI/CD процессов.',
    skills: ['Kubernetes', 'Terraform', 'Ansible', 'GitLab CI', 'AWS', 'Prometheus'],
    url: 'https://hh.ru/vacancy/456789123',
    publishedAt: '2024-01-13T09:00:00Z',
    createdAt: '2024-01-13T11:00:00Z',
    responses: 67,
    views: 890,
    isAnalyzed: false,
    isFavorite: false,
    status: 'new'
  },
  {
    id: '4',
    externalId: '321654987',
    source: 'hh',
    title: 'Data Scientist',
    company: 'Тинькофф',
    salary: { from: 200000, to: 320000, currency: 'RUB' },
    experience: '1-3 года',
    employment: 'Полная занятость',
    schedule: 'Гибридный график',
    location: 'Москва',
    description: 'Ищем Data Scientist для работы над ML-моделями в продукте.',
    skills: ['Python', 'PyTorch', 'TensorFlow', 'SQL', 'Spark', 'MLflow'],
    url: 'https://hh.ru/vacancy/321654987',
    publishedAt: '2024-01-12T16:00:00Z',
    createdAt: '2024-01-12T18:00:00Z',
    responses: 234,
    views: 3200,
    isAnalyzed: true,
    matchScore: 65,
    isFavorite: true,
    status: 'applied'
  },
  {
    id: '5',
    externalId: '159753486',
    source: 'hh',
    title: 'Fullstack Developer (Node.js + React)',
    company: 'Авито',
    salary: { from: 220000, to: 300000, currency: 'RUB' },
    experience: '1-3 года',
    employment: 'Полная занятость',
    schedule: 'Офис',
    location: 'Москва',
    description: 'Разработка веб-приложений для внутренних сервисов компании.',
    skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'MongoDB'],
    url: 'https://hh.ru/vacancy/159753486',
    publishedAt: '2024-01-11T11:00:00Z',
    createdAt: '2024-01-11T13:00:00Z',
    responses: 178,
    views: 2100,
    isAnalyzed: false,
    isFavorite: false,
    status: 'new'
  },
  {
    id: '6',
    externalId: '753951456',
    source: 'hh',
    title: 'QA Automation Engineer',
    company: 'Ozon',
    salary: { from: 180000, to: 260000, currency: 'RUB' },
    experience: '1-3 года',
    employment: 'Полная занятость',
    schedule: 'Удаленная работа',
    location: 'Любой город',
    description: 'Автоматизация тестирования для e-commerce платформы.',
    skills: ['Python', 'Selenium', 'Pytest', 'Allure', 'API Testing', 'CI/CD'],
    url: 'https://hh.ru/vacancy/753951456',
    publishedAt: '2024-01-10T08:00:00Z',
    createdAt: '2024-01-10T10:00:00Z',
    responses: 95,
    views: 1340,
    isAnalyzed: true,
    matchScore: 45,
    isFavorite: false,
    status: 'rejected'
  }
]

export const mockSearchQueries: SearchQuery[] = [
  {
    id: '1',
    keyword: 'Frontend Developer React',
    location: 'Москва',
    experience: '1-3 года',
    employment: 'Полная занятость',
    schedule: 'Удаленная работа',
    isActive: true,
    interval: 60,
    lastRun: '2024-01-15T14:00:00Z',
    nextRun: '2024-01-15T15:00:00Z',
    createdAt: '2024-01-01T10:00:00Z',
    vacanciesFound: 156
  },
  {
    id: '2',
    keyword: 'Python Backend FastAPI',
    location: 'Санкт-Петербург',
    isActive: true,
    interval: 120,
    lastRun: '2024-01-15T12:00:00Z',
    nextRun: '2024-01-15T14:00:00Z',
    createdAt: '2024-01-05T15:00:00Z',
    vacanciesFound: 89
  },
  {
    id: '3',
    keyword: 'DevOps Kubernetes',
    isActive: false,
    interval: 60,
    createdAt: '2024-01-10T09:00:00Z',
    vacanciesFound: 45
  }
]

export const mockResume: Resume = {
  id: '1',
  title: 'Frontend Developer',
  fullName: 'Иванов Иван Иванович',
  position: 'Senior Frontend Developer',
  experience: '5 лет коммерческой разработки. Последние 3 года работаю с React и TypeScript. Участвовал в разработке высоконагруженных веб-приложений.',
  skills: ['JavaScript', 'TypeScript', 'React', 'Next.js', 'Node.js', 'GraphQL', 'REST API', 'Git', 'Docker'],
  education: 'МГТУ им. Н.Э. Баумана, Информатика и системы управления, 2019',
  about: 'Увлеченный разработчик с опытом создания сложных веб-приложений. Постоянно изучаю новые технологии и best practices.',
  contacts: {
    email: 'ivan@example.com',
    phone: '+7 (999) 123-45-67',
    telegram: '@ivan_dev'
  },
  rawText: '',
  createdAt: '2024-01-01T10:00:00Z',
  updatedAt: '2024-01-15T12:00:00Z',
  isActive: true
}

export const mockAnalytics: Analytics = {
  totalVacancies: 456,
  newToday: 23,
  analyzed: 312,
  applied: 15,
  avgSalary: 285000,
  topSkills: [
    { skill: 'React', count: 234 },
    { skill: 'TypeScript', count: 198 },
    { skill: 'Python', count: 167 },
    { skill: 'Node.js', count: 145 },
    { skill: 'PostgreSQL', count: 123 },
    { skill: 'Docker', count: 112 },
    { skill: 'Kubernetes', count: 89 },
    { skill: 'AWS', count: 78 }
  ],
  vacanciesByDate: [
    { date: '2024-01-09', count: 34 },
    { date: '2024-01-10', count: 45 },
    { date: '2024-01-11', count: 38 },
    { date: '2024-01-12', count: 52 },
    { date: '2024-01-13', count: 41 },
    { date: '2024-01-14', count: 67 },
    { date: '2024-01-15', count: 23 }
  ],
  vacanciesBySource: [
    { source: 'hh.ru', count: 456 }
  ],
  vacanciesByExperience: [
    { experience: 'Без опыта', count: 45 },
    { experience: '1-3 года', count: 178 },
    { experience: '3-6 лет', count: 156 },
    { experience: '6+ лет', count: 77 }
  ]
}
